<a href="https://colab.research.google.com/github/KotaShimomura/pythondata/blob/master/no1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
sq = [1,4,9,16,25]
sq

[1, 4, 9, 16, 25]

In [ ]:
sq[0]

1

In [ ]:
sq[2:]

[9, 16, 25]

In [ ]:
sq[:3]

[1, 4, 9]

In [ ]:
sq[-2:]

[16, 25]

In [ ]:
sq[:-1]

[1, 4, 9, 16]

In [ ]:
sq.append(36)
sq

[1, 4, 9, 16, 25, 36]

In [ ]:
ls0 = [1,1.2,'123',[1,2,3]]
ls0

[1, 1.2, '123', [1, 2, 3]]

In [ ]:
ls1=[1,2,3]
ls2 = ls1
ls2.append(4)
ls1,ls2

([1, 2, 3, 4], [1, 2, 3, 4])

In [ ]:
ls1=[1,2,3]
ls2 = ls1.copy()
ls2.append(4)
ls1,ls2

([1, 2, 3], [1, 2, 3, 4])

In [ ]:
room = {'Yamashita': 6405, 'Matsui': 6407}
room['Matsui']

6407

In [ ]:
room['akitosi'] = 6406
room

{'Matsui': 6407, 'Yamashita': 6405, 'akitosi': 6406}

In [ ]:
list(room)

['Yamashita', 'Matsui', 'akitosi']

In [ ]:
'Matsui' in room

True

In [ ]:
'kota' in room

False

In [ ]:
x = 1
if x < 0:
    print('Negative')
elif x == 0:
    print('Zero')
else:
    print('Positive')

Positive


In [ ]:
sq = [1,4,9,16,25]
for s in sq:
  print(s)

1
4
9
16
25


In [ ]:
for i in range(len(sq)):
  print(sq[i])
  #lenで配列の長さを調べ、rangeでインデックスの範囲を指定

1
4
9
16
25


In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
room = {'Yamashita': 6405, 'Matsui': 6407}
for key, value in room.items():
    print(key, value)

Yamashita 6405
Matsui 6407


In [ ]:
def abs(x):
  if x < 0:
    return -x
  else:
    return x

abs(-10)


10

In [ ]:
def abs(x,y):
  if x < 0 and y < 0:
    return -x, -y
  elif x < 0:
    return -x, y
  elif y < 0:
    return x,-y
  else:
    return -x, -y

x, y = abs(-10, -20)
print(x,y)


10 20


In [ ]:
def sum(x, y, z=0, w=10):
    return x + y + z + w

print(sum(10, 20))
print(sum(10, 20, 30))
print(sum(10, 20, 30, 40))

40
70
100


In [ ]:
sum(10,20,w=40)

70

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array([1,2,3,4,5,6], dtype='float64')
a

array([1., 2., 3., 4., 5., 6.])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.array([1,2,3,4,5,6])
a.reshape(a.size, 1)
#横ベクトルを立てベクトルに変換

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

演習

In [ ]:
def is_leap(a):
  if a % 4 == 0:
    return True
  elif a % 100 == 0:
    return False
  elif a % 400 == 0:
    return True
  else: 
    return False


In [ ]:
y = 2020
is_leap(y)

True

In [ ]:
for i in range(5):
  for j in range(i+1):
    print("*",end='')
  print()

*
**
***
****
*****


In [ ]:
def odd_list(dict):
  odd_list = []
  for key, value in dict.items():
    if value % 2 == 1:
      odd_list.append(key)
  return odd_list

In [ ]:
dict = {'Apple': 1, 'Orange': 2, 'Banana': 3, 'Grape': 4, 'Melon': 5, 'Strawberry': 6}
odd_list(dict)

['Apple', 'Banana', 'Melon']

In [ ]:
import numpy as np
def flatten(a):
  return a.reshape(1, a.size)[0]

In [ ]:
# このプログラムを実行する
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
flatten(a)

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
def abs_array(a):
  shape = a.shape
  abs_list = []
  for v in flatten(a):
    if v < 0:
        v = v * -1
    abs_list.append(v)
  abs_array = np.array(abs_list)
  return abs_array.reshape(shape)


In [ ]:
# このプログラムを実行する
import numpy as np
a1 = np.array([[1, -2, 3], [-4, -5, 6]])
print(abs_array(a1))
a2 = np.array([[-1, 2], [-3, -4], [5, -6]])
print(abs_array(a2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
